# Generated by Django 5.1.5 on 2025-01-22 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plant", "0003_alter_plant_layout"),
    ]

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("top", models.PositiveIntegerField()),
                ("left", models.PositiveIntegerField()),
                ("direction", models.PositiveIntegerField(max_length=20)),
                ("description", models.TextField()),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plant.plant"
                    ),
                ),
            ],
        ),
    ]
