# Generated by Django 5.1.5 on 2025-01-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0002_alter_camera_direction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
