# Generated by Django 5.1.5 on 2025-01-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="layout",
            field=models.ImageField(blank=True, null=True, upload_to="static/images/"),
        ),
    ]
